// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie-ticket-sales.proto

package fisher.kafka.streams.proto;

public final class MovieTicketSalesOuterClass {
  private MovieTicketSalesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovieTicketSalesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fisher.kafka.streams.proto.MovieTicketSales)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>int32 release_year = 2;</code>
     * @return The releaseYear.
     */
    int getReleaseYear();

    /**
     * <code>int32 total_sales = 3;</code>
     * @return The totalSales.
     */
    int getTotalSales();
  }
  /**
   * Protobuf type {@code fisher.kafka.streams.proto.MovieTicketSales}
   */
  public  static final class MovieTicketSales extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fisher.kafka.streams.proto.MovieTicketSales)
      MovieTicketSalesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MovieTicketSales.newBuilder() to construct.
    private MovieTicketSales(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieTicketSales() {
      title_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MovieTicketSales();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MovieTicketSales(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 16: {

              releaseYear_ = input.readInt32();
              break;
            }
            case 24: {

              totalSales_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fisher.kafka.streams.proto.MovieTicketSalesOuterClass.internal_static_fisher_kafka_streams_proto_MovieTicketSales_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fisher.kafka.streams.proto.MovieTicketSalesOuterClass.internal_static_fisher_kafka_streams_proto_MovieTicketSales_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales.class, fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELEASE_YEAR_FIELD_NUMBER = 2;
    private int releaseYear_;
    /**
     * <code>int32 release_year = 2;</code>
     * @return The releaseYear.
     */
    public int getReleaseYear() {
      return releaseYear_;
    }

    public static final int TOTAL_SALES_FIELD_NUMBER = 3;
    private int totalSales_;
    /**
     * <code>int32 total_sales = 3;</code>
     * @return The totalSales.
     */
    public int getTotalSales() {
      return totalSales_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (releaseYear_ != 0) {
        output.writeInt32(2, releaseYear_);
      }
      if (totalSales_ != 0) {
        output.writeInt32(3, totalSales_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (releaseYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, releaseYear_);
      }
      if (totalSales_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalSales_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales)) {
        return super.equals(obj);
      }
      fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales other = (fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (getReleaseYear()
          != other.getReleaseYear()) return false;
      if (getTotalSales()
          != other.getTotalSales()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + RELEASE_YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseYear();
      hash = (37 * hash) + TOTAL_SALES_FIELD_NUMBER;
      hash = (53 * hash) + getTotalSales();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fisher.kafka.streams.proto.MovieTicketSales}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fisher.kafka.streams.proto.MovieTicketSales)
        fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSalesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fisher.kafka.streams.proto.MovieTicketSalesOuterClass.internal_static_fisher_kafka_streams_proto_MovieTicketSales_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fisher.kafka.streams.proto.MovieTicketSalesOuterClass.internal_static_fisher_kafka_streams_proto_MovieTicketSales_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales.class, fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales.Builder.class);
      }

      // Construct using fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = "";

        releaseYear_ = 0;

        totalSales_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fisher.kafka.streams.proto.MovieTicketSalesOuterClass.internal_static_fisher_kafka_streams_proto_MovieTicketSales_descriptor;
      }

      @java.lang.Override
      public fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales getDefaultInstanceForType() {
        return fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales.getDefaultInstance();
      }

      @java.lang.Override
      public fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales build() {
        fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales buildPartial() {
        fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales result = new fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales(this);
        result.title_ = title_;
        result.releaseYear_ = releaseYear_;
        result.totalSales_ = totalSales_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales) {
          return mergeFrom((fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales other) {
        if (other == fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (other.getReleaseYear() != 0) {
          setReleaseYear(other.getReleaseYear());
        }
        if (other.getTotalSales() != 0) {
          setTotalSales(other.getTotalSales());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private int releaseYear_ ;
      /**
       * <code>int32 release_year = 2;</code>
       * @return The releaseYear.
       */
      public int getReleaseYear() {
        return releaseYear_;
      }
      /**
       * <code>int32 release_year = 2;</code>
       * @param value The releaseYear to set.
       * @return This builder for chaining.
       */
      public Builder setReleaseYear(int value) {
        
        releaseYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 release_year = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReleaseYear() {
        
        releaseYear_ = 0;
        onChanged();
        return this;
      }

      private int totalSales_ ;
      /**
       * <code>int32 total_sales = 3;</code>
       * @return The totalSales.
       */
      public int getTotalSales() {
        return totalSales_;
      }
      /**
       * <code>int32 total_sales = 3;</code>
       * @param value The totalSales to set.
       * @return This builder for chaining.
       */
      public Builder setTotalSales(int value) {
        
        totalSales_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total_sales = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalSales() {
        
        totalSales_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fisher.kafka.streams.proto.MovieTicketSales)
    }

    // @@protoc_insertion_point(class_scope:fisher.kafka.streams.proto.MovieTicketSales)
    private static final fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales();
    }

    public static fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieTicketSales>
        PARSER = new com.google.protobuf.AbstractParser<MovieTicketSales>() {
      @java.lang.Override
      public MovieTicketSales parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MovieTicketSales(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieTicketSales> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieTicketSales> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fisher.kafka.streams.proto.MovieTicketSalesOuterClass.MovieTicketSales getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fisher_kafka_streams_proto_MovieTicketSales_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fisher_kafka_streams_proto_MovieTicketSales_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030movie-ticket-sales.proto\022\032fisher.kafka" +
      ".streams.proto\"L\n\020MovieTicketSales\022\r\n\005ti" +
      "tle\030\001 \001(\t\022\024\n\014release_year\030\002 \001(\005\022\023\n\013total" +
      "_sales\030\003 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fisher_kafka_streams_proto_MovieTicketSales_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fisher_kafka_streams_proto_MovieTicketSales_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fisher_kafka_streams_proto_MovieTicketSales_descriptor,
        new java.lang.String[] { "Title", "ReleaseYear", "TotalSales", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
